name: bwabat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.3

  freezed_annotation: ^2.4.1
  # for dependency injection
  get_it: ^7.6.4

  # Networking
  dio: ^5.3.3
  retrofit: ^4.3.0
  pretty_dio_logger: ^1.4.0
  # localization
  intl: ^0.19.0
  easy_localization: ^3.0.7
  # for splash screen
  flutter_native_splash: ^2.4.1
  # An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.0.15
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.0
  firebase_core: ^3.2.0
  # Flutter library to load and cache network images.
  cached_network_image: ^3.3.1
  # reading and writing simple key-value pairs
  shared_preferences: ^2.3.2
  # provides API to store data in secure storage.
  flutter_secure_storage: ^9.2.2
  # easy way to add shimmer effect
  bloc: ^8.1.4
    

  injectable: ^2.4.2
  equatable: ^2.0.5
  animate_do: ^3.3.4
  vector_graphics: ^1.1.11+1
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.3.0
  flutter_animate: ^4.5.1
  pretty_animated_text: ^2.0.0

  


dev_dependencies:

  # A build system for Dart code generation and modular compilation
  build_runner: ^2.4.13
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.5.2
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  retrofit_generator: ^9.0.0
  very_good_analysis: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
flutter_assets:
  assets_path: assets/svgs/
  output_path: lib/core/resources/
  filename: app_assets.dart
  field_prefix: